// Request body for POST /api/v1/transactions/transfer
// IDs are Long on backend — typed as number on frontend
// amount is a String on backend — sent as string from frontend
// reference is a required unique idempotency key — generated by frontend
export interface TransferRequest {
  sourceAccountId: number
  destinationAccountId: number
  // Amount sent as string — backend expects String for BigDecimal parsing
  amount: string
  currency: 'NGN'
  // Unique idempotency key — generated via crypto.randomUUID() on the frontend
  reference: string
  description?: string
}

// Validation errors for the transfer form — one field at a time
export interface TransferFormErrors {
  sourceAccountId?: string
  destinationAccountId?: string
  amount?: string
  description?: string
}